mutation CreateNewPost($authorId: UUID, $content: String!, $imageUrls: [String], $postType: String!, $preparationTime: String, $rating: Int, $restaurantName: String, $tags: [String], $title: String!) @auth(level: USER) {
  post_insert(data: {authorId: $authorId, content: $content, imageUrls: $imageUrls, postType: $postType, preparationTime: $preparationTime, rating: $rating, restaurantName: $restaurantName, tags: $tags, title: $title, createdAt_expr: "request.time"})
}

query GetPostsByCategory($categoryId: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  categories(where: {id: {eq: $categoryId}}) {
    posts_via_PostCategory {
      id
      title
      content
      author {
        id
        username
      }
    }
  }
}

mutation UpdateUserBio($bio: String) @auth(level: USER) {
  user_update(key: {id_expr: "auth.uid"}, data: {bio: $bio})
}

query GetPostsByCurrentUser @auth(level: USER) {
  posts(where: {authorId: {eq_expr: "auth.uid"}}) {
    id
    title
    content
    createdAt
  }
}